---
 - name: Installing and launch Metricbeat
   hosts: webservers
   become: yes
   tasks:

    - name: Download metricbeat .deb file
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

    - name: Install metricbeat .deb
      command: dpkg -i metricbeat-7.4.0-amd64.deb

    - name: Drop in metricbeat-config.yml
      copy:
        src: /etc/ansible/files/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml

    - name: Enable and configure Docker Module
      command: metricbeat modules enable docker

    - name: Setup metricbeat
      command: metricbeat setup -e

    - name: start metricbeat service
      command: service metricbeat start
